---
-  name: installation of nodeexporter
   become: yes
   hosts: all
   vars:
    -  node_url: "https://github.com/prometheus/node_exporter/releases/download/v1.4.0/node_exporter-1.4.0.linux-amd64.tar.gz"
      
   tasks: 
    -  name: updating packages
       apt:
         update_cache: yes
         state: present
    -  name: Downloading prometheus version
       get_url:
         url: "{{ node_url }}"
         dest: /home/ansible 
    -  name: unarchieve the prometheus url
       unarchive:
         src: "/home/ansible/node_exporter-1.4.0.linux-amd64.tar.gz"
         dest: "/home/ansible"
         remote_src: yes
    - name: copy node exporter 
      ansible.builtin.copy:
        src: /home/ansible/node_exporter-1.4.0.linux-amd64/node_exporter
        dest: /usr/local/bin/
    -  name: creating a user node_exporter
       user:
         name: node_exporter
         create_home: no
         shell: /bin/false  
    - name: create a group node_exporter
      group:
        name: node_exporter
        state: present       
    - name: copying service file
      template:
        src: nodeexporter.service.j2
        dest: /etc/systemd/system/node_exporter.service
        owner: node_exporter 
        group: node_exporter
        mode: '0744'
    - name: starting prometheus service
      systemd:
        name: node_exporter.service
        daemon_reload: yes 
        state: started        
           
            
 

   